name: mqtt_template_2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mqtt_client: ^9.7.2
  platform_device_id: ^1.0.1
  provider: ^6.0.4
  internet_connectivity_checker: ^0.1.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/